	spring.application.name=ORDERSERVICE

server.port=9091

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.config.import=optional:configserver:http://localhost:9094

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Feign Timeout
spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=5000

# Circuit Breaker
resilience4j.circuitbreaker.instances.paymentService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.paymentService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.paymentService.sliding-window-size=10
resilience4j.circuitbreaker.instances.paymentService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.paymentService.permitted-number-of-calls-in-half-open-state=3

management.endpoints.web.exposure.include=*
management.health.circuitbreakers.enabled=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.profiles.active=dev
# spring.profiles.active=test
# spring.profiles.active=prod

# Day 8 - User Service Retry
resilience4j.retry.instances.userService.max-attempts=3
resilience4j.retry.instances.userService.wait-duration=500ms

# Day 8 - User Service Circuit Breaker
resilience4j.circuitbreaker.instances.userService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.userService.sliding-window-size=10
resilience4j.circuitbreaker.instances.userService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.userService.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.userService.ignore-exceptions=feign.FeignException$NotFound

# Day 9 - User Service Bulkhead
resilience4j.bulkhead.instances.userService.max-concurrent-calls=5
resilience4j.bulkhead.instances.userService.max-wait-duration=0